version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: always
    environment:
      - 'POSTGRES_DB=ecfarm'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8090:80"
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=balu88@outlook.com'
      - 'PGADMIN_DEFAULT_PASSWORD=Dec@091220'
      - 'PGADMIN_CONFIG_SERVER_MODE=False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge

